# Generated by Django 3.2 on 2021-11-30 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_orderproductitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90, 'Широта должна быть в диапазоне от -90 до 90'), django.core.validators.MaxValueValidator(90, 'Широта должна быть в диапазоне от -90 до 90')], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180, 'Долгота должна быть в диапазоне от -180 до 180'), django.core.validators.MaxValueValidator(180, 'Долгота должна быть в диапазоне от -180 до 180')], verbose_name='Долгота'),
        ),
    ]
