# Generated by Django 3.2 on 2021-12-05 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20211205_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличный'), ('cashless', 'безналичный'), ('credit', 'кредит')], db_index=True, max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderproductitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
