# Generated by Django 3.2 on 2021-12-06 19:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20211205_2309'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('summed', django.db.models.manager.Manager()),
            ],
        ),
    ]
