# Generated by Django 3.2 on 2022-01-25 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20211205_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
